### ISSUE TITLE
Provide software justification for cyberduck

### ISSUE THREAD

**Issue by gbinal** [18F/ED-API-Program#105]
cc @nikkichurchwell

**Comment by gbinal** [comment]
What we're in need of is an AWS S3 client.  Similar in function to a FTP client, an S3 client provides a user interface for uploading and managing static files that are hosted in Amazon S3. to avoid having to only use the command line. We use Amazon S3 for this project due to its low cost, ease of use, ubiquity, immense scalability, and because it is available through the cloud.gov service.  

Cyberduck has the advantages of being: 
- free
- open source
- available on both mac and windows computers 
- well-established with a solidly positive reputation.  

Another windows-based s3 client can work in its place, but may lack some of these advantages.

**Comment by nikkichurchwell** [comment]
Great! Can you also provide a few sentences about the purpose of a AWS S3 client and why it is essential to our work?

**Comment by gbinal** [comment]
Done.  Check out ^^^ and see if that helps.
