### ISSUE TITLE
finalize v0.1 launch data picks 

### ISSUE THREAD

**Issue by gbinal** [18F/ED-API-Program#111]

**Comment by gbinal** [comment]
Note - 
- http://nces.ed.gov/collegenavigator/
- https://nces.ed.gov/programs/digest/current_tables.asp
  - https://nces.ed.gov/programs/digest/d15/tables/dt15_101.10.asp?current=yes
- https://nces.ed.gov/ipeds/datacenter/DataFiles.aspx
- my brother's keeper 
- http://nces.ed.gov/programs/crimeindicators/mobile/
- hd2015.csv
- usershared.....csv
- ef2014a.csv

**Comment by metzgr** [comment]
mbk data:

http://www2.ed.gov/rschstat/statistics/surveys/mbk/index.html

there is a process/commitments in place to keep these updated. we've gotten approval to use one or more of these datasets. one question they have is how many we can do.

after they receive that info they'll come up with preferred candidates. i think it'll be a good idea to go back to them with our own recommendations in case we identify data that has a wider utility for developers.

My list (non-nces sources, too...):

Percentage of 18- to 24-year-olds who have not completed high school by sex and race/ethnicity, 2000–2014

Percentage of 18- to 24-year-olds enrolled in 2- and 4-year colleges by sex and race/ethnicity, 2000–2013

Percentage of 18- to 24-year-olds who have completed a bachelor’s or higher degree by sex and race/ethnicity, 2000–2014

Percentage of U.S. resident bachelor’s degrees conferred in science, technology, engineering, and mathematics by sex and race/ethnicity, 1999–2000 through 2011–13

Percentage of 18- to 24-year-olds who were neither enrolled in school nor working by sex and race/ethnicity, 2000–2014 (so-called disconnected youth)

Labor force participation rates for young adults ages 18–24 by age, sex, and race/ethnicity, 1980–2013 annual averages

Imprisonment rates of 18- to 24-year-olds sentenced to more than 1 year under the jurisdiction of state correctional authorities per 100,000 by sex and race/ethnicity, 2000–2012

**Comment by gbinal** [comment]
We're hoping to have a decision on this by the end of this week.

**Comment by metzgr** [comment]
Update: final list will be decided by tomorrow.

**Comment by gbinal** [comment]
From [this page](http://www2.ed.gov/rschstat/statistics/surveys/mbk/index.html): 
- [Percentage of 18- to 24-year-olds who have not completed high school by sex and race/ethnicity, 2000–2014](http://www2.ed.gov/rschstat/statistics/surveys/mbk/Less-than-highschool_2015.csv)
  - [endpoint](https://api.ed.gov/data/less-than-highschool_2015?api_key=DEMO_KEY1)
- [Percentage of 18- to 24-year-olds enrolled in 2- and 4-year colleges by sex and race/ethnicity, 2000–2013](http://www2.ed.gov/rschstat/statistics/surveys/mbk/College-enrollment-rates_2015.csv)
  - [endpoint](https://api.ed.gov/data/college-enrollment-rates_2015?api_key=DEMO_KEY1) - needs work
- [Percentage of 18- to 24-year-olds who have completed a bachelor’s or higher degree by sex and race/ethnicity, 2000–2014](http://www2.ed.gov/rschstat/statistics/surveys/mbk/Bachelors-or-higher-degrees-among-young-adults_2015.csv)
  - [endpoint](https://api.ed.gov/data/bachelors-or-higher-degrees-among-young-adults_2015?api_key=DEMO_KEY1) - needs work
- [Percentage of U.S. resident bachelor’s degrees conferred in science, technology, engineering, and mathematics by sex and race/ethnicity, 1999–2000 through 2011–13](http://www2.ed.gov/rschstat/statistics/surveys/mbk/STEM-bachelors-degrees_2015.csv)
  - [endpoint](https://api.ed.gov/data/stem-bachelors-degrees_2015?api_key=bNoA8XxhBXQjcBmTsIcqFEgDdPU8jJVOpMG7makC)
- [Percentage of 18- to 24-year-olds who were neither enrolled in school nor working by sex and race/ethnicity, 2000–2014 (so-called disconnected youth)](http://www2.ed.gov/rschstat/statistics/surveys/mbk/Youth-neither-enrolled-in-school-nor-working_2015.csv)
  - [endpoint](https://api.ed.gov/data/youth-neither-enrolled-in-school-nor-working_2015?api_key=DEMO_KEY1) - needs work
- [Labor force participation rates for young adults ages 18–24 by age, sex, and race/ethnicity, 1980–2013 annual averages](http://www2.ed.gov/rschstat/statistics/surveys/mbk/LFPR_rates_verfied_2014_0731_1335.csv)
  - [endpoint](https://api.ed.gov/data/lfpr_rates_verfied_2014_0731_1335?api_key=DEMO_KEY1)
- [Imprisonment rates of 18- to 24-year-olds sentenced to more than 1 year under the jurisdiction of state correctional authorities per 100,000 by sex and race/ethnicity, 2000–2012](https://inventory.data.gov/dataset/ab727e43-c577-416d-ab17-837f1451a1da/resource/793ab04c-04fe-4e19-ad75-e5815d03570c)
  - [endpoint](https://api.ed.gov/data/userssharedsdfimprisonmentratesof1824yosre20002012?api_key=DEMO_KEY1)

**Comment by gbinal** [comment]
Notes: 
- For `Percentage of 18- to 24-year-olds enrolled in 2- and 4-year colleges by sex and race/ethnicity, 2000–2013`, there appears to be two datasets in that table with that name.  I believe the first to be the correct dataset and am using it.  
- The parentheses in the header columns of the three datasets with `needs work` notations above are breaking the api.  I'm removing the `(in thousands)` notation from the first row of the dataset and we should include it in the documentation.  
- Something is wrong with the STEM API and I can't figure out what

**Comment by gbinal** [comment]
We want to include these: 
- the my brother's keeper data 
- the crdc data
- the school directory data

**Comment by gbinal** [comment]
This is complete.  The loose issues, I'm moving to a new issue
