### ISSUE TITLE
Training: Using Github as a CMS

### ISSUE THREAD

**Issue by metzgr** [18F/ED-API-Program#125]
- [ ] What is GitHub Pages?
  - [ ] Benefits
- [ ] Creating a microsite
- [ ] Editing a microsite 
- [ ] Creating a new page
- [ ] Managing a page's metadata
- [ ] Managing the site's style 
- [ ] Review other examples 
- [ ] Issue Tracker 
- [ ] Pull Requests 
- [ ] Markdown vs. HTML 
- [ ] Hosting files 
- [ ] Understanding the files that make up Jekyll 
- [ ] Advanced management
  - [ ] CNAME-ing
  - [ ] Transferring the Repo
  - [ ] Managing Access
  - [ ] HTTPS 

Notes and more information located [here](https://github.com/18F/ED-API-Program/blob/master/deliverables/develop-hub-notes.md).

**Comment by gbinal** [comment]
Done on 9-29-16
