### ISSUE TITLE
Update the autoapi instance with the api.data.gov url

### ISSUE THREAD

**Issue by gbinal** [18F/ED-API-Program#14]

**Comment by gbinal** [comment]
I've done a first pass at this, using `api.18f.gov/ed/` ([example](https://api.18f.gov/ed/data/dummy-data-1?api_key=DEMO_KEY1)), but we'll update it with `api.ed.gov` whenever that's ready.

**Comment by gbinal** [comment]
@toolness - can you update https://autoapi.apps.cloud.gov/swagger-ui to use `api.18f.gov/ed/data` and let us know when it's updated?

**Comment by toolness** [comment]
Ok, I think this is done! For future reference, I had to target the app's org and space and run:

```
cf set-env autoapi AUTOAPI_HOST api.18f.gov/ed/data
cf restage autoapi
```
