### ISSUE TITLE
Decide on API base url

### ISSUE THREAD

**Issue by gbinal** [18F/ED-API-Program#15]
_api.agency.gov_ is recommended

**Comment by gbinal** [comment]
The advantages to setting up api.agency.gov as the base URL are:  
- It's a clean, consistent base that is developer friendly and intuitive.  
- By setting this aside as a base URL, it allows us to reserve it for a unified URL structure for future APIs.  For instance, we can set up our data API at api.ed.gov/data/~ and eventually migrate the college scorecard api to api.ed.gov/collegescorecard/~, while still leaving plenty of space for other future APIs at api.ed.gov/x/~ and api.ed.gov/y/~.

**Comment by gbinal** [comment]
Below are basic instructions.  Once the correct staffer at ED has been identified who can assist with them, please put them in touch with me.  

# 
- **CNAME a subdomain (recommended):** If you can dedicate a subdomain to API requests, this is the most straightforward approach. As an example, you might setup `api.agency.gov`. This domain name would be CNAMEd to api.data.gov's servers. We would accept requests for that domain name, and then assuming they pass our validations (api key checks, rate limiting, etc), we would then pass the requests to your underlying API servers (which should be [secured](https://github.com/18F/api.data.gov/wiki/User-Manual:-Agencies#securing-your-api-backend) to only accept connections from api.data.gov's servers).
  - CNAME settings: The CNAME you'll need to use won't actually be to api.data.gov directly. So please [contact us](https://api.data.gov/contact/) and we can quickly work with you to get a CNAME in place for your domain.
  - HTTPS: We will automatically handle SSL registration and renewal for your API subdomain after the CNAME is setup. No need to purchase or send us SSL certificates.
  - Non-API website content (for example, a home page, documentation, or a developer hub) can also be proxied to a separate destination (for example, GitHub Pages). See [hosting website content on your CNAMEd subdomain](https://github.com/18F/api.data.gov/wiki/User-Manual:-Agencies#hosting-website-content-on-your-cnamed-subdomain) below.

More information can be found [here](https://github.com/18F/api.data.gov/wiki/User-Manual:-Agencies).  Especially note: 
- [Setting up HTTPS](https://github.com/18F/api.data.gov/wiki/User-Manual:-Agencies#setting-up-https-on-your-own-domain-name)
- [Securing the API backend](https://github.com/18F/api.data.gov/wiki/User-Manual:-Agencies#securing-your-api-backend)

**Comment by metzgr** [comment]
Thanks! OCIO accepted these base URLs. David Harrity at ED is the right person to work with.

**Comment by gbinal** [comment]
We've formally submitted the request and await its completion.

**Comment by gbinal** [comment]
The URL has been decided on and the request submitted so I'm going to go ahead and close this issue since it was focused on the choice.  If IT doesn't follow through on the request in a timely fashion, we may want to open an issue for completing the CNAME setup.
