### ISSUE TITLE
ensure core team has github accounts 

### ISSUE THREAD

**Issue by gbinal** [18F/ED-API-Program#70]

**Comment by metzgr** [comment]
metzgr

**Comment by gbinal** [comment]
Please also set up - https://github.com/blog/1614-two-factor-authentication
- You can use authy or google authenticator

**Comment by nikkichurchwell** [comment]
nikkichurchwell

**Comment by ismorgan** [comment]
ismorgan

**Comment by gbinal** [comment]
It'll be great to get Emily, too, but I can go ahead and mark this closed.
