### ISSUE TITLE
Survey pre-existing APIs

### ISSUE THREAD

**Issue by gbinal** [18F/ED-API-Program#75]

**Comment by gbinal** [comment]
Known APIs: 
- There's a bunch linked on www.ed.gov/developers
  - Note documentation at http://docs.ckan.org/en/latest/maintaining/datastore.html
- https://collegescorecard.ed.gov/data/documentation/
- ED ARCGIS server - http://nces.ed.gov/arcgis/rest/services

**Comment by gbinal** [comment]
To search for others, we'll employ a number of google queries:

For ed.gov 
- ["web service" site:ed.gov](https://www.google.com/search?q=%22web+service%22+site%3Aed.gov&oq=%22web+service%22+sit&aqs=chrome.0.69i59l3j0j69i57j0.4391j0j9&sourceid=chrome&ie=UTF-8)
- ["web services" site:ed.gov](https://www.google.com/search?q=%22web+services%22+site%3Aed.gov&oq=%22web+services%22+site%3Aed.gov&aqs=chrome..69i57.425j0j9&sourceid=chrome&ie=UTF-8)
- ["api" site:ed.gov](https://www.google.com/search?q=%22api%22+site%3Aed.gov&oq=%22api%22+site%3Aed.gov&aqs=chrome..69i57.534j0j9&sourceid=chrome&ie=UTF-8)
- ["application programming interface" site:ed.gov](https://www.google.com/search?q=%22application+programming+interface%22+site%3Aed.gov&oq=%22application+programming+interface%22+site%3Aed.gov&aqs=chrome..69i57.419j0j9&sourceid=chrome&ie=UTF-8)
- ["application program interface" site:ed.gov](https://www.google.com/search?q=%22application+program+interface%22+site%3Aed.gov&oq=%22application+program+interface%22+site%3Aed.gov&aqs=chrome..69i57.320j0j9&sourceid=chrome&ie=UTF-8)
- ["wsdl" site:ed.gov](https://www.google.com/search?q=%22wsdl%22+site%3Aed.gov&oq=%22wsdl%22+site%3Aed.gov&aqs=chrome..69i57.446j0j9&sourceid=chrome&ie=UTF-8)
- ["wadl" site:ed.gov](https://www.google.com/search?q=%22wadl%22+site%3Aed.gov&oq=%22wadl%22+site%3Aed.gov&aqs=chrome..69i57.243j0j9&sourceid=chrome&ie=UTF-8)

For the other domains:  
- ["web service" site:CHILDSTATS.GOV OR site:EDPUBS.GOV OR site:EDUCATION.GOV OR site:FAFSA.GOV OR site:FSAPUBS.GOV OR site:G5.GOV OR site:NAGB.GOV OR site:NATIONSREPORTCARD.GOV OR site:STUDENTAID.GOV OR site:STUDENTLOANS.GOV](https://www.google.com/search?q=%22web+service%22+site%3ACHILDSTATS.GOV+OR+site%3AEDPUBS.GOV+OR+site%3AEDUCATION.GOV+OR+site%3AFAFSA.GOV+OR+site%3AFSAPUBS.GOV+OR+site%3AG5.GOV+OR+site%3ANAGB.GOV+OR+site%3ANATIONSREPORTCARD.GOV+OR+site%3ASTUDENTAID.GOV+OR+site%3ASTUDENTLOANS.GOV&oq=%22web+service%22+site%3ACHILDSTATS.GOV+OR+site%3AEDPUBS.GOV+OR+site%3AEDUCATION.GOV+OR+site%3AFAFSA.GOV+OR+site%3AFSAPUBS.GOV+OR+site%3AG5.GOV+OR+site%3ANAGB.GOV+OR+site%3ANATIONSREPORTCARD.GOV+OR+site%3ASTUDENTAID.GOV+OR+site%3ASTUDENTLOANS.GOV&aqs=chrome..69i57j69i59.394j0j9&sourceid=chrome&ie=UTF-8)
- ["web services" site:CHILDSTATS.GOV OR site:EDPUBS.GOV OR site:EDUCATION.GOV OR site:FAFSA.GOV OR site:FSAPUBS.GOV OR site:G5.GOV OR site:NAGB.GOV OR site:NATIONSREPORTCARD.GOV OR site:STUDENTAID.GOV OR site:STUDENTLOANS.GOV](https://www.google.com/search?q=%22web+services%22+site%3ACHILDSTATS.GOV+OR+site%3AEDPUBS.GOV+OR+site%3AEDUCATION.GOV+OR+site%3AFAFSA.GOV+OR+site%3AFSAPUBS.GOV+OR+site%3AG5.GOV+OR+site%3ANAGB.GOV+OR+site%3ANATIONSREPORTCARD.GOV+OR+site%3ASTUDENTAID.GOV+OR+site%3ASTUDENTLOANS.GOV&oq=%22web+services%22+site%3ACHILDSTATS.GOV+OR+site%3AEDPUBS.GOV+OR+site%3AEDUCATION.GOV+OR+site%3AFAFSA.GOV+OR+site%3AFSAPUBS.GOV+OR+site%3AG5.GOV+OR+site%3ANAGB.GOV+OR+site%3ANATIONSREPORTCARD.GOV+OR+site%3ASTUDENTAID.GOV+OR+site%3ASTUDENTLOANS.GOV&aqs=chrome..69i57j69i59.543j0j9&sourceid=chrome&ie=UTF-8)
- ["api" site:CHILDSTATS.GOV OR site:EDPUBS.GOV OR site:EDUCATION.GOV OR site:FAFSA.GOV OR site:FSAPUBS.GOV OR site:G5.GOV OR site:NAGB.GOV OR site:NATIONSREPORTCARD.GOV OR site:STUDENTAID.GOV OR site:STUDENTLOANS.GOV](https://www.google.com/search?q=%22api%22+site%3ACHILDSTATS.GOV+OR+site%3AEDPUBS.GOV+OR+site%3AEDUCATION.GOV+OR+site%3AFAFSA.GOV+OR+site%3AFSAPUBS.GOV+OR+site%3AG5.GOV+OR+site%3ANAGB.GOV+OR+site%3ANATIONSREPORTCARD.GOV+OR+site%3ASTUDENTAID.GOV+OR+site%3ASTUDENTLOANS.GOV&oq=%22api%22+site%3ACHILDSTATS.GOV+OR+site%3AEDPUBS.GOV+OR+site%3AEDUCATION.GOV+OR+site%3AFAFSA.GOV+OR+site%3AFSAPUBS.GOV+OR+site%3AG5.GOV+OR+site%3ANAGB.GOV+OR+site%3ANATIONSREPORTCARD.GOV+OR+site%3ASTUDENTAID.GOV+OR+site%3ASTUDENTLOANS.GOV&aqs=chrome..69i57j69i59.426j0j9&sourceid=chrome&ie=UTF-8)
- ["application programming interface" site:CHILDSTATS.GOV OR site:EDPUBS.GOV OR site:EDUCATION.GOV OR site:FAFSA.GOV OR site:FSAPUBS.GOV OR site:G5.GOV OR site:NAGB.GOV OR site:NATIONSREPORTCARD.GOV OR site:STUDENTAID.GOV OR site:STUDENTLOANS.GOV](https://www.google.com/search?q=%22application+programming+interface%22+site%3ACHILDSTATS.GOV+OR+site%3AEDPUBS.GOV+OR+site%3AEDUCATION.GOV+OR+site%3AFAFSA.GOV+OR+site%3AFSAPUBS.GOV+OR+site%3AG5.GOV+OR+site%3ANAGB.GOV+OR+site%3ANATIONSREPORTCARD.GOV+OR+site%3ASTUDENTAID.GOV+OR+site%3ASTUDENTLOANS.GOV&oq=%22application+programming+interface%22+site%3ACHILDSTATS.GOV+OR+site%3AEDPUBS.GOV+OR+site%3AEDUCATION.GOV+OR+site%3AFAFSA.GOV+OR+site%3AFSAPUBS.GOV+OR+site%3AG5.GOV+OR+site%3ANAGB.GOV+OR+site%3ANATIONSREPORTCARD.GOV+OR+site%3ASTUDENTAID.GOV+OR+site%3ASTUDENTLOANS.GOV&aqs=chrome..69i57.7255j0j9&sourceid=chrome&ie=UTF-8)
- ["application program interface" site:CHILDSTATS.GOV OR site:EDPUBS.GOV OR site:EDUCATION.GOV OR site:FAFSA.GOV OR site:FSAPUBS.GOV OR site:G5.GOV OR site:NAGB.GOV OR site:NATIONSREPORTCARD.GOV OR site:STUDENTAID.GOV OR site:STUDENTLOANS.GOV](https://www.google.com/search?q=%22application+program+interface%22+site%3ACHILDSTATS.GOV+OR+site%3AEDPUBS.GOV+OR+site%3AEDUCATION.GOV+OR+site%3AFAFSA.GOV+OR+site%3AFSAPUBS.GOV+OR+site%3AG5.GOV+OR+site%3ANAGB.GOV+OR+site%3ANATIONSREPORTCARD.GOV+OR+site%3ASTUDENTAID.GOV+OR+site%3ASTUDENTLOANS.GOV&oq=%22application+program+interface%22+site%3ACHILDSTATS.GOV+OR+site%3AEDPUBS.GOV+OR+site%3AEDUCATION.GOV+OR+site%3AFAFSA.GOV+OR+site%3AFSAPUBS.GOV+OR+site%3AG5.GOV+OR+site%3ANAGB.GOV+OR+site%3ANATIONSREPORTCARD.GOV+OR+site%3ASTUDENTAID.GOV+OR+site%3ASTUDENTLOANS.GOV&aqs=chrome..69i57.390j0j9&sourceid=chrome&ie=UTF-8)
- ["wsdl" site:CHILDSTATS.GOV OR site:EDPUBS.GOV OR site:EDUCATION.GOV OR site:FAFSA.GOV OR site:FSAPUBS.GOV OR site:G5.GOV OR site:NAGB.GOV OR site:NATIONSREPORTCARD.GOV OR site:STUDENTAID.GOV OR site:STUDENTLOANS.GOV](https://www.google.com/search?q=%22wsdl%22+site%3ACHILDSTATS.GOV+OR+site%3AEDPUBS.GOV+OR+site%3AEDUCATION.GOV+OR+site%3AFAFSA.GOV+OR+site%3AFSAPUBS.GOV+OR+site%3AG5.GOV+OR+site%3ANAGB.GOV+OR+site%3ANATIONSREPORTCARD.GOV+OR+site%3ASTUDENTAID.GOV+OR+site%3ASTUDENTLOANS.GOV&oq=%22wsdl%22+site%3ACHILDSTATS.GOV+OR+site%3AEDPUBS.GOV+OR+site%3AEDUCATION.GOV+OR+site%3AFAFSA.GOV+OR+site%3AFSAPUBS.GOV+OR+site%3AG5.GOV+OR+site%3ANAGB.GOV+OR+site%3ANATIONSREPORTCARD.GOV+OR+site%3ASTUDENTAID.GOV+OR+site%3ASTUDENTLOANS.GOV&aqs=chrome..69i57.415j0j9&sourceid=chrome&ie=UTF-8)
- ["wadl" site:CHILDSTATS.GOV OR site:EDPUBS.GOV OR site:EDUCATION.GOV OR site:FAFSA.GOV OR site:FSAPUBS.GOV OR site:G5.GOV OR site:NAGB.GOV OR site:NATIONSREPORTCARD.GOV OR site:STUDENTAID.GOV OR site:STUDENTLOANS.GOV](https://www.google.com/search?q=%22wadl%22+site%3ACHILDSTATS.GOV+OR+site%3AEDPUBS.GOV+OR+site%3AEDUCATION.GOV+OR+site%3AFAFSA.GOV+OR+site%3AFSAPUBS.GOV+OR+site%3AG5.GOV+OR+site%3ANAGB.GOV+OR+site%3ANATIONSREPORTCARD.GOV+OR+site%3ASTUDENTAID.GOV+OR+site%3ASTUDENTLOANS.GOV&oq=%22wadl%22+site%3ACHILDSTATS.GOV+OR+site%3AEDPUBS.GOV+OR+site%3AEDUCATION.GOV+OR+site%3AFAFSA.GOV+OR+site%3AFSAPUBS.GOV+OR+site%3AG5.GOV+OR+site%3ANAGB.GOV+OR+site%3ANATIONSREPORTCARD.GOV+OR+site%3ASTUDENTAID.GOV+OR+site%3ASTUDENTLOANS.GOV&aqs=chrome..69i57.283j0j9&sourceid=chrome&ie=UTF-8)

**Comment by gbinal** [comment]
- It's worth checking with the authors of [this blog post](http://blog.ed.gov/2015/03/how-weve-improved-the-customer-experience-for-eds-grant-opportunities/) to ensure there weren't other APIs made.  
- Did the [FSA FOTW API](https://ifap.ed.gov/eannouncements/attachments/20142015StateAPIInvitation.pdf) ever come into being?    [More info [here](https://ifap.ed.gov/eannouncements/031113StateAPI1314.html)]
- It's worth checking with Denise Hill (author of [this](https://www.ifap.ed.gov/presentations/attachments/03SDCWebServicesUpdate.pdf)) to ask if any others.

**Comment by metzgr** [comment]
Was on http://opendatainception.io/ and found that ED has a pretty robust open data portal (using Esri's platform): http://data.deptofed.opendata.arcgis.com/

Some of the datasets come with APIs http://data.deptofed.opendata.arcgis.com/datasets/28b5cc066a6d461fb072de6fd7863572_0 through Geoservices (http://geoservices.github.io/)

We're talking to Ross Santy at IES tomorrow and will learn more then.

**Comment by metzgr** [comment]
When I asked about http://blog.ed.gov/2015/03/how-weve-improved-the-customer-experience-for-eds-grant-opportunities/: We had to stop the grants system project in late February/early March of this year for which that API work was planned, due to lack of sufficient resources. At one point we did talk to Grants.gov about HHS building an API for their education grant data, and they were amenable to doing so in their future work, but we had to stop well before that work would have commenced.

**Comment by metzgr** [comment]
FSA FOTW API never came into being.

**Comment by gbinal** [comment]
Thanks for these updates, @metzgr. We wouldn't want to have left them out if they were out there.
