### ISSUE TITLE
investigate the inventory.data.gov use

### ISSUE THREAD

**Issue by gbinal** [18F/ED-API-Program#84]
- how the files have been added/updated 
- who at ED has been working on that

**Comment by metzgr** [comment]
Just to confirm: did you find the information you needed here? Or do we need to reach out to people on our side?

**Comment by gbinal** [comment]
Sorry for the confusion.  Yes, I found out what is needed and no, there's no need to reach out on your end right now.  I'll add more updates here directly.

**Comment by gbinal** [comment]
It looks like the following ED addresses have access:  
- victor.zapanta@  - _who I believe is no longer active there_
- i3@
- ivy.morgan@ - _who we'll probably talk to more about this  :)_

The files are updated through the inventory.data.gov admin interface.
